---
driver:
  name: lxd_cli
  config:
    security.nesting: true

transport:
  name: sftp

provisioner:
  name: ansible_playbook
  roles_path: ../
  hosts: test-kitchen
  # ansible_verbose: true
  ansible_verbose: false
  ansible_verbosity: 3
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  require_ansible_omnibus: true
  # planned for deprecation per https://docs.chef.io/workstation/config_yml_kitchen/
  require_chef_omnibus: true
  require_chef_for_busser: true
  require_ruby_for_busser: false
  chef_omnibus_url: https://omnitruck.chef.io/install.sh
  enable_yum_epel: true
  ansible_connection: ssh

platforms:
  - name: ubuntu-22.04
  - name: ubuntu-20.04
  - name: ubuntu-18.04
  # - name: centos-7
  # - name: centos-6
  ## "Failed to complete #create action: [Broken pipe] on default-alpine-34"
  ## do we have python2 in default image?
  # - name: alpine-3.4

suites:
  - name: default
    run_list:
    attributes:
