---

# - debug: var=current

- name: Download lxc image
  ansible.builtin.command: "lxc image copy {{ image }} local: --alias={{ alias }}"
  when: current is defined and current.stdout.find(alias) == -1 and alias is defined
