---
## when Ansible 2.2.0 released: use lxd_container module

- name: Lxd images published
  when: "' ' + publishalias + ' ' not in imagelist.stdout"
  block:
    - name: Start lxc instance {{ guest }}
      ansible.builtin.shell:  # noqa no-changed-when command-instead-of-shell
        cmd: "{{ item }}"
      with_items:
        - "lxc init {{ template }} {{ guest }}"
        - "lxc start {{ guest }}"
        ## mostly for images from linuxcontainers.org + centos, necessary for CI testing, especially travis
        ##  --stdin not supported on xenial
        # - "openssl rand -base64 48 | lxc exec {{ guest }} -- passwd root --stdin"
        - "openssl rand -base64 48 | perl -ne 'print \"$_\" x2' | lxc exec {{ guest }} -- passwd root"
      when: '" " + guest " " not in lxclist.stdout'

    - name: Configure lxc instance {{ guest }}  # noqa no-changed-when
      ansible.builtin.command:
        cmd: "lxc exec {{ guest }} -- {{ item }}"
      with_items: "{{ shellcmds }}"
      # ignore_errors: true

    - name: Stop and publish lxc instance {{ guest }}  # noqa no-changed-when
      ansible.builtin.command:
        cmd: "{{ item }}"
      with_items:
        - "lxc stop {{ guest }} --force"
        - "lxc publish {{ guest }} --alias {{ publishalias }}"
        - "lxc delete {{ guest }}"
